// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('GEMINI_API_KEY'),
    appId: '1:408503604102:web:465e68d2007d38ab029207',
    messagingSenderId: '408503604102',
    projectId: 'cvity-fb4d5',
    authDomain: 'cvity-fb4d5.firebaseapp.com',
    storageBucket: 'cvity-fb4d5.firebasestorage.app',
    measurementId: 'G-6SEJYCSL23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('GEMINI_API_KEY');,
    appId: '1:408503604102:android:e440aaf38098ba11029207',
    messagingSenderId: '408503604102',
    projectId: 'cvity-fb4d5',
    storageBucket: 'cvity-fb4d5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('GEMINI_API_KEY');,
    appId: '1:408503604102:ios:101183cb8804e3a0029207',
    messagingSenderId: '408503604102',
    projectId: 'cvity-fb4d5',
    storageBucket: 'cvity-fb4d5.firebasestorage.app',
    iosBundleId: 'com.example.cvity',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('GEMINI_API_KEY');,
    appId: '1:408503604102:ios:101183cb8804e3a0029207',
    messagingSenderId: '408503604102',
    projectId: 'cvity-fb4d5',
    storageBucket: 'cvity-fb4d5.firebasestorage.app',
    iosBundleId: 'com.example.cvity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('GEMINI_API_KEY');,
    appId: '1:408503604102:web:cee62b8ba9323902029207',
    messagingSenderId: '408503604102',
    projectId: 'cvity-fb4d5',
    authDomain: 'cvity-fb4d5.firebaseapp.com',
    storageBucket: 'cvity-fb4d5.firebasestorage.app',
    measurementId: 'G-JP7ZEWX048',
  );
}
